Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/docker-linux"

  config.vm.define "service" do |vm_service|
    vm_service.vm.provision "shell", inline: "bash /vagrant/service/restore.sh", privileged: false
    vm_service.vm.provision "shell", inline: "bash /vagrant/service/build.sh", privileged: false
  end

  config.vm.define "docker" do |vm_docker|
    vm_docker.vm.provision "shell", inline: "bash /vagrant/docker/restore.sh", privileged: false
    vm_docker.vm.provision "shell", inline: "bash /vagrant/docker/build.sh", privileged: false
  end
end
