directory = File.dirname(__FILE__)

require "#{directory}/../../../../src/vagrant"
require "#{directory}/../../../../samples/vagrant"

VagrantDeployment.defaults_include(
  'machines' => {
    'server' => VagrantLinuxServerMachine.defaults,
    'desktop' => VagrantLinuxDesktopMachine.defaults,
    'docker' => VagrantLinuxDockerMachine.defaults,
  }
)

VagrantDeployment.configure(directory)
