directory = File.dirname(__FILE__)

require "#{directory}/../vagrant"

VagrantMachine.defaults_include(
  'provisioners' => {
    'chef_policyfile' => {},
  }
)

VagrantDeployment.configure(directory, 'component' => 'chef-policyfile-provisioner')
