directory = File.dirname(__FILE__)

require "#{directory}/../vagrant"

VagrantMachine.defaults_include(
  'provisioners' => {
    'shell' => {
      'inline' => 'echo "Hello World!"',
    },
  }
)

VagrantDeployment.configure(directory, 'component' => 'shell')
