# ENV["VAGRANT_DEFAULT_PROVIDER"] = "hyperv"

private_network_bridge = ENV["VAGRANT_PRIVATE_NETWORK_BRIDGE"] || "Default Switch"

synced_folder_disabled = ENV["VAGRANT_SYNCED_FOLDER_DISABLED"] || false
synced_folder_username = ENV["VAGRANT_SYNCED_FOLDER_USERNAME"] || ENV["USERNAME"]
synced_folder_password = ENV["VAGRANT_SYNCED_FOLDER_PASSWORD"]

Vagrant.configure("2") do |config|
  config.vm.network "private_network", bridge: private_network_bridge

  if synced_folder_disabled
    config.vm.synced_folder ".", "/vagrant", disabled: true
  else
    config.vm.synced_folder ".", "/vagrant", type: "smb", smb_username: synced_folder_username, smb_password: synced_folder_password
  end
end
