directory = File.dirname(__FILE__)

require "#{directory}/../../../../src/vagrant"
require "#{directory}/../../../../samples/vagrant"

VagrantDeployment.defaults_include(
  'machines' => {
    'default' => VagrantLinuxDockerMachine.defaults,
  }
)

VagrantDeployment.configure(directory)
