Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/docker-linux"

  config.vm.provision "shell", path: "./core/restore.sh", privileged: false

  config.vm.provider "virtualbox" do |provider_virtualbox, config_override|
    config_override.vm.network "forwarded_port", guest: 8500, host: 58500, auto_correct: true
    config_override.vm.network "forwarded_port", guest: 9002, host: 59002, auto_correct: true
  end
end
