Vagrant.configure("2") do |config|
  config.vm.define "default", primary: true do |vm_default|
    vm_default.vm.box = "gusztavvargadr/docker-windows"
    # vm_default.vm.box_version = "~> 2010.2102.0" # 2022
    # vm_default.vm.box_version = "~> 2010.1809.0" # 2019
  end

  config.vm.provision "shell", inline: "systeminfo"
  config.vm.provision "shell", inline: "docker version"
  config.vm.provision "shell", inline: "docker run --rm hello-world"
end
