Vagrant.configure('2') do |config|
  config.vm.box = 'dummy'

  config.vm.provider :azure do |azure, override|
    azure.location = 'westeurope'

    azure.vm_image_urn = 'Canonical:UbuntuServer:16.04-LTS:latest'
    azure.vm_size = 'Standard_B1s'

    override.ssh.private_key_path = '~/.ssh/azure'
    override.vm.synced_folder '.', '/vagrant', type: 'rsync'
  end
end
