directory = File.dirname(__FILE__)

require "#{directory}/../../../src/vagrant"
require "#{directory}/../../vagrant"

VagrantDeployment.defaults_include(
  'machines' => {
    'default' => VagrantLinuxServerMachine.defaults,
  }
)

VagrantDeployment.configure(directory)
