directory = File.dirname(__FILE__)

require "#{directory}/../../../src/vagrant"
require "#{directory}/../../../samples/vagrant"

VagrantDeployment.defaults_include(
  'machines' => {
    'windows' => VagrantWindowsDockerMachine.defaults,
    'linux' => VagrantLinuxDockerMachine.defaults,
  }
)

VagrantDeployment.configure(directory)
