directory = File.dirname(__FILE__)

load "#{directory}/../../src/core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "latest-deprecated", autostart: false do |config|
    config.vm.box = "gusztavvargadr/sql-server"
  end

  config.vm.define "2019-developer-windows-2022-deprecated", autostart: false do |config|
    config.vm.box = "gusztavvargadr/sql-server-20190-developer-windows-server"
  end

  config.vm.define "2019-developer-windows-2022-core-deprecated", autostart: false do |config|
    config.vm.box = "gusztavvargadr/sql-server-2019-developer-windows-server-core"
  end

  config.vm.provision "shell", inline: <<-EOH
    sqlcmd -Q "SELECT @@VERSION"
  EOH
end
