Vagrant.configure("2") do |config|
  config.vm.define "default", primary: true do |vm_default|
    vm_default.vm.box = "gusztavvargadr/windows-server-core"
    # vm_default.vm.box_version = "~> 2102.0" # 2022
    # vm_default.vm.box_version = "~> 1809.0" # 2019
  end

  config.vm.define "2022", autostart: false do |vm_2022|
    vm_2022.vm.box = "gusztavvargadr/windows-server-2022-standard-core"
  end

  config.vm.define "2019", autostart: false do |vm_2019|
    vm_2019.vm.box = "gusztavvargadr/windows-server-2019-standard-core"
  end

  config.vm.provision "shell", inline: "systeminfo"
end
