server_count = 1
client_count = 1

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/docker-linux"

  config.vm.provider "virtualbox" do |provider_virtualbox|
    provider_virtualbox.cpus = 2
    provider_virtualbox.memory = 1024
  end

  config.vm.provider "hyperv" do |provider_hyperv|
    provider_hyperv.cpus = 2
    provider_hyperv.memory = 1024
  end

  config.vm.provision "shell", inline: "bash /vagrant/service/restore.sh", privileged: false

  (1..server_count).each do |i|
    config.vm.define "server-#{i}" do |vm_server|
      vm_server.vm.hostname = "server-#{i}"

      vm_server.vm.provision "shell", inline: "bash /vagrant/service/build.sh server", privileged: false
    end
  end

  (1..client_count).each do |i|
    config.vm.define "client-#{i}" do |vm_client|
      vm_client.vm.hostname = "client-#{i}"

      vm_client.vm.provision "shell", inline: "bash /vagrant/service/build.sh client", privileged: false
    end
  end
end
