Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/docker-linux"

  config.vm.provider "virtualbox" do |provider_virtualbox|
    provider_virtualbox.cpus = 2
    provider_virtualbox.memory = 1024
  end

  config.vm.provider "hyperv" do |provider_hyperv|
    provider_hyperv.cpus = 2
    provider_hyperv.memory = 1024
  end

  config.vm.provision "shell", path: "./core/restore.sh", privileged: false

  config.vm.define "server-1" do |vm_server_1|
    vm_server_1.vm.hostname = "server-1"
  end

  config.vm.define "server-2" do |vm_server_1|
    vm_server_1.vm.hostname = "server-2"
  end

  config.vm.define "server-3" do |vm_server_1|
    vm_server_1.vm.hostname = "server-3"
  end

  config.vm.define "client-1" do |vm_server_1|
    vm_server_1.vm.hostname = "client-1"
  end

  config.vm.define "client-2" do |vm_server_1|
    vm_server_1.vm.hostname = "client-2"
  end
end
