name 'gusztavvargadr_vagrant_git'
maintainer 'Gusztav Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Git'
long_description 'Installs/Configures Git'
version '0.1.0'
