directory = File.dirname(__FILE__)

require "#{directory}/../vagrant"

VagrantDeployment.defaults_include(
  'machines' => {
    'windows' => VagrantDockerWindowsMachine.defaults,
    'linux' => VagrantDockerLinuxMachine.defaults,
  }
)

VagrantDeployment.configure(directory)
