directory = File.dirname(__FILE__)

require "#{directory}/../vagrant"

VagrantMachine.defaults_include(
  'provisioners' => {
    'chef_zero' => {
      'run_list' => 'recipe[hello_world::default]',
    },
  }
)

VagrantDeployment.configure(directory)
