Vagrant.configure("2") do |config|
  config.vm.define "dhcp" do |config_vm|
    config_vm.vm.box = "gusztavvargadr/windows-server"

    config_vm.vm.provider "hyperv" do |config_provider|
      config_provider.cpus = 2
      config_provider.memory = 1024
      config_provider.auto_start_action = "StartIfRunning"
    end

    config_vm.vm.provision "shell", path: "./dhcp.ps1"
  end
end
