directory = File.dirname(__FILE__)

require "#{directory}/../vagrant"

VagrantMachine.defaults_include(
  'synced_folders' => {
    '/vagrant-smb' => {
      'source' => '.',
      'type' => 'smb',
    },
  }
)

VagrantDeployment.configure(directory, 'component' => 'smb', 'stack' => 'synced_folders')
