directory = File.dirname(__FILE__)

require "#{directory}/../vagrant"

VagrantDeployment.defaults_include(
  'machines' => {
    'windows' => VagrantDockerWindowsMachine.defaults,
    'linux' => VagrantDockerLinuxMachine.defaults,
  }
)

VagrantMachine.defaults_include(
  'provisioners' => {
    'docker' => {
      'runs' => [
        'name' => 'hello-world',
        'image' => 'hello-world',
        'daemonize' => 'false',
        'restart' => 'no',
      ],
    },
  }
)

VagrantDeployment.configure(directory, 'component' => 'docker')
