directory = File.dirname(__FILE__)

load "#{directory}/../../src/core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "latest", autostart: false do |config|
    config.vm.box = "gusztavvargadr/visual-studio"
  end

  config.vm.define "2022-community-windows-11", autostart: false do |config|
    config.vm.box = "gusztavvargadr/visual-studio-2022-community-windows-11"
  end

  # deprecated 2511
  config.vm.define "2022-community-windows-10", autostart: false do |config|
    config.vm.box = "gusztavvargadr/visual-studio-2022-community-windows-10"
  end

  config.vm.provision "shell", inline: <<-EOH
    dotnet --info
    dotnet --list-sdks
  EOH
end
