version: '3'

services:
  consul-core:
    image: ${CONSUL_CORE_IMAGE}
    build:
      context: ./core
      dockerfile: ./Dockerfile
      args:
        BASE: ${CONSUL_IMAGE_NAME}:${CONSUL_IMAGE_VERSION}
    restart: on-failure
    volumes:
      - core:/consul/core
    networks:
      - core

  consul-bootstrap:
    image: ${CONSUL_BOOTSTRAP_IMAGE}
    build:
      context: ./bootstrap
      dockerfile: ./Dockerfile
      args:
        BASE: ${CONSUL_CORE_IMAGE}
    restart: on-failure
    volumes:
      - core:/consul/core
    networks:
      - core

  consul-server:
    image: ${CONSUL_SERVER_IMAGE}
    build:
      context: ./server
      dockerfile: ./Dockerfile
      args:
        BASE: ${CONSUL_CORE_IMAGE}
    restart: on-failure
    volumes:
      - core:/consul/core
    networks:
      - core

  consul-client:
    image: ${CONSUL_CLIENT_IMAGE}
    build:
      context: ./client
      dockerfile: ./Dockerfile
      args:
        BASE: ${CONSUL_CORE_IMAGE}
    restart: on-failure
    volumes:
      - core:/consul/core
    networks:
      - core
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"

volumes:
  core:

networks:
  core:
