directory = File.dirname(__FILE__)

require "#{directory}/../../../src/vagrant"
require "#{directory}/../../../samples/vagrant"

VagrantDeployment.defaults_include(
  'machines' => {
    'dhcp' => VagrantWindowsServerMachine.defaults,
  }
)

VagrantDeployment.configure(directory)
