directory = File.dirname(__FILE__)

require "#{directory}/../vagrant"

VagrantMachine.defaults_include(
  'provisioners' => {
    'file' => {
      'source' => 'hello-world.txt',
      'destination' => '/tmp/hello-world.txt',
    },
  }
)

VagrantDeployment.configure(directory, 'component' => 'file-provisioner')
