directory = File.dirname(__FILE__)

ENV["VAGRANT_PROVIDER_CPUS"] = "4"
ENV["VAGRANT_PROVIDER_MEMORY"] = "8192"
ENV["VAGRANT_PROVIDER_NESTED_VIRTUALIZATION"] = "false"
ENV["VAGRANT_PROVIDER_LINKED_CLONE"] = "false"
ENV["VAGRANT_PROVIDER_SYNCED_FOLDER_DISABLED"] = "true"

# ENV["VAGRANT_PROVIDER_CPUS"] = "8"
# ENV["VAGRANT_PROVIDER_MEMORY"] = "16384"
# ENV["VAGRANT_PROVIDER_NESTED_VIRTUALIZATION"] = "true"
# ENV["VAGRANT_PROVIDER_LINKED_CLONE"] = "false"
# ENV["VAGRANT_PROVIDER_SYNCED_FOLDER_DISABLED"] = "true"

load "#{directory}/../../src/core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "windows", autostart: false do |config|
    config.vm.box = "gusztavvargadr/kitchen-windows-2022"

    config.vm.provision "shell", inline: <<-EOH
      . { iwr -useb https://gist.github.com/gusztavvargadr/1f0d7dddc7f48549368eaaedf19bfe55/raw/provision.ps1 } | iex
    EOH
  end

  config.vm.define "ubuntu", autostart: false do |config|
    config.vm.box = "gusztavvargadr/kitchen-ubuntu-2204"

    config.vm.provision "shell", inline: <<-EOH
      curl -Ls https://gist.github.com/gusztavvargadr/1f0d7dddc7f48549368eaaedf19bfe55/raw/provision.sh | bash -s
    EOH
  end
end
