directory = File.dirname(__FILE__)

ENV["VAGRANT_PROVIDER_CPUS"] = "4"
ENV["VAGRANT_PROVIDER_MEMORY"] = "8192"
ENV["VAGRANT_PROVIDER_NESTED_VIRTUALIZATION"] = "false"

# ENV["VAGRANT_PROVIDER_CPUS"] = "8"
# ENV["VAGRANT_PROVIDER_MEMORY"] = "16384"
# ENV["VAGRANT_PROVIDER_NESTED_VIRTUALIZATION"] = "true"

load "#{directory}/../../src/core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "windows-2025", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-server-2025-standard"

    config.vm.provision "shell", inline: <<-EOH
      $env:CHEF_POLICY="gusztavvargadr_development"
      . { iwr -useb https://gist.github.com/gusztavvargadr/1f0d7dddc7f48549368eaaedf19bfe55/raw/provision.ps1 } | iex
    EOH
  end

  config.vm.define "windows-2022", autostart: false do |config|
    config.vm.box = "gusztavvargadr/windows-server-2022-standard"

    config.vm.provision "shell", inline: <<-EOH
      $env:CHEF_POLICY="gusztavvargadr_development"
      . { iwr -useb https://gist.github.com/gusztavvargadr/1f0d7dddc7f48549368eaaedf19bfe55/raw/provision.ps1 } | iex
    EOH
  end

  config.vm.define "ubuntu-2404", autostart: false do |config|
    config.vm.box = "gusztavvargadr/development-ubuntu-2404"

    config.vm.provision "shell", inline: <<-EOH
      uname -a
      lsb_release -a

      lshw -short
      lscpu
      lsmem

      export CHEF_POLICY="gusztavvargadr_development"
      curl -Ls https://gist.github.com/gusztavvargadr/1f0d7dddc7f48549368eaaedf19bfe55/raw/provision.sh | bash -s

      git --version

      dotnet --info
      dotnet tool list --global

      docker --version
    EOH
  end

  config.vm.define "ubuntu-2204", autostart: false do |config|
    config.vm.box = "gusztavvargadr/development-ubuntu-2204"

    config.vm.provision "shell", inline: <<-EOH
      uname -a
      lsb_release -a

      lshw -short
      lscpu
      lsmem

      export CHEF_POLICY="gusztavvargadr_development"
      curl -Ls https://gist.github.com/gusztavvargadr/1f0d7dddc7f48549368eaaedf19bfe55/raw/provision.sh | bash -s

      git --version

      dotnet --info
      dotnet tool list --global

      docker --version
    EOH
  end
end
