Vagrant.configure("2") do |config|
  config.vm.define "server", primary: true do |server|
    server.vm.box = "gusztavvargadr/ubuntu-server"
  end

  config.vm.define "desktop", autostart: false do |desktop|
    desktop.vm.box = "gusztavvargadr/ubuntu-desktop"
  end

  config.vm.define "docker", autostart: false do |docker|
    docker.vm.box = "gusztavvargadr/docker-linux"
  end

  config.vm.provision "shell", inline: <<-EOH
    uname -a
    lsb_release -a
    lshw
  EOH
end
