directory = File.dirname(__FILE__)

load "#{directory}/../../src/core.Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.define "server", autostart: false do |config|
    config.vm.box = "gusztavvargadr/ubuntu-server-2204-lts"
  end

  config.vm.define "desktop", autostart: false do |config|
    config.vm.box = "gusztavvargadr/ubuntu-desktop-2204-lts"
  end

  config.vm.provision "shell", inline: <<-EOH
    uname -a
    lsb_release -a

    lshw -short
    lscpu
    lsmem

    apt list --installed
  EOH
end
