directory = File.dirname(__FILE__)

require "#{directory}/../vagrant"

VagrantMachine.defaults_include(
  'synced_folders' => {
    '/vagrant-default' => {
      'source' => '.',
    },
  }
)

VagrantDeployment.configure(directory, 'environment' => 'default.synced_folders.vagrant')
