Vagrant.configure('2') do |config|
  config.vm.define 'windows10ee', autostart: false do |windows10ee|
    windows10ee.vm.box = 'gusztavvargadr/windows10ee'

    windows10ee.vm.provider 'virtualbox' do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define 'windows2012r2se', autostart: false do |windows2012r2se|
    windows2012r2se.vm.box = 'gusztavvargadr/windows2012r2se'

    windows2012r2se.vm.provider 'virtualbox' do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
