# ENV["VAGRANT_DEFAULT_PROVIDER"] = "virtualbox"

virtualbox_linked_clone = ENV["VAGRANT_VIRTUALBOX_LINKED_CLONE"] || false

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |provider_virtualbox|
    provider_virtualbox.linked_clone = virtualbox_linked_clone

    # v.customize [ "modifyvm", :id, "--nested-hw-virt", "on" ]
  end
end
