Vagrant.configure("2") do |config|
  config.vm.define "default", primary: true do |vm_default|
    vm_default.vm.box = "gusztavvargadr/windows-10"
    # vm_default.vm.box_version = "~> 2102.0" # 21H2
    # vm_default.vm.box_version = "~> 2101.0" # 21H1
  end

  config.vm.define "21h2", autostart: false do |vm_21h2|
    vm_21h2.vm.box = "gusztavvargadr/windows-10-21h2-enterprise"
  end

  config.vm.define "21h1", autostart: false do |vm_21h1|
    vm_21h1.vm.box = "gusztavvargadr/windows-10-21h1-enterprise"
  end

  config.vm.provision "shell", inline: "systeminfo"
end
