name 'gusztavvargadr_vagrant_octopus'
maintainer 'Gusztav Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Octopus'
long_description 'Installs/Configures Octopus'
version '0.1.0'
