directory = File.dirname(__FILE__)

require "#{directory}/../vagrant"

VagrantMachine.defaults_include(
  'box' => VagrantWindowsDesktopMachine.defaults['box'],
  'synced_folders' => {
    "#{directory}/../../.." => '/src/gusztavvargadr/vagrant',
  },
  'provisioners' => {
    'chef_policyfile_install' => {
    },
    'reload' => {},
    'chef_policyfile_configure' => {
      'path' => 'Policyfile_configure.rb',
    },
  }
)

VagrantProvider.defaults_include(
  'memory' => 8192,
  'cpus' => 4
)

VagrantDeployment.configure(directory)
