directory = File.dirname(__FILE__)

require "#{directory}/../vagrant"

VagrantDeployment.defaults_include(
  'machines' => {
    'windows' => VagrantWindowsDesktopMachine.defaults,
    'linux' => VagrantLinuxDesktopMachine.defaults,
  }
)

VagrantMachine.defaults_include(
  'providers' => {
    'virtualbox' => {
      'memory' => 4096,
      'cpus' => 2,
    },
    'hyperv' => {
      'memory' => 4096,
      'cpus' => 2,
    },
    'azure' => {
      'size' => 'Standard_B2s',
    },
  }
)

VagrantDeployment.configure(directory, 'component' => 'desktop')
