directory = File.dirname(__FILE__)

require "#{directory}/../vagrant"

VagrantDeployment.defaults_include(
  'machines' => {
    'linux' => {
      'box' => VagrantLinuxDesktopMachine.defaults['box'],
    },
    'windows' => {
      'box' => VagrantWindowsDesktopMachine.defaults['box'],
    },
  }
)

VagrantProvider.defaults_include(
  'memory' => 8192,
  'cpus' => 4
)

VagrantDeployment.configure(directory, 'component' => 'desktop', 'stack' => 'machines')
