directory = File.dirname(__FILE__)

require "#{directory}/../../../src/vagrant"

VagrantMachine.defaults_include(
  'providers' => {
    'virtualbox' => {},
    'hyperv' => {},
  }
)

VagrantDeployment.configure(directory)
