Vagrant.configure("2") do |config|
  config.vm.define "server", primary: true do |server|
    server.vm.box = "gusztavvargadr/windows-server-core"
  end

  config.vm.define "desktop", autostart: false do |desktop|
    desktop.vm.box = "gusztavvargadr/windows-10"
  end

  config.vm.define "docker", autostart: false do |docker|
    docker.vm.box = "gusztavvargadr/docker-windows"
  end

  config.vm.provision "shell", inline: <<-EOH
    cmd /c ver
    systeminfo
  EOH
end
