directory = File.dirname(__FILE__)

require "#{directory}/../../../../src/vagrant"
require "#{directory}/../../../../samples/vagrant"

VagrantDeployment.defaults_include(
  'machines' => {
    'server' => VagrantWindowsServerMachine.defaults,
    'desktop' => VagrantWindowsDesktopMachine.defaults,
    'docker' => VagrantWindowsDockerMachine.defaults,
  }
)

VagrantDeployment.configure(directory)
